// Embers of Aldreth: boss rewards (generated by tools/build_loot.py from design/bosses.py; edit those, not this file).
// Every boss kill rolls aldreth:boss/t<tier> at the corpse, on top of the boss's own unique drops. Credit: the killer is a player, or a player
// is within 48 blocks (summoners and pet builds count). The Ender Dragon's table lands on the exit fountain.
const ALD_BOSS_TIER = {
 "mowziesmobs:ferrous_wroughtnaut": 2,
 "twilightforest:naga": 2,
 "twilightforest:lich": 3,
 "twilightforest:minoshroom": 3,
 "twilightforest:hydra": 4,
 "twilightforest:knight_phantom": 3,
 "twilightforest:ur_ghast": 4,
 "twilightforest:alpha_yeti": 3,
 "twilightforest:snow_queen": 4,
 "undergarden:forgotten_guardian": 4,
 "aether:slider": 4,
 "aether:valkyrie_queen": 4,
 "aether:sun_spirit": 5,
 "blue_skies:summoner": 4,
 "blue_skies:starlit_crusher": 5,
 "blue_skies:alchemist": 4,
 "blue_skies:arachnarch": 5,
 "cataclysm:ignis": 5,
 "cataclysm:netherite_monstrosity": 5,
 "cataclysm:the_harbinger": 5,
 "cataclysm:the_leviathan": 5,
 "cataclysm:ancient_remnant": 5,
 "cataclysm:ender_guardian": 6,
 "cataclysm:maledictus": 6,
 "cataclysm:scylla": 6,
 "minecraft:warden": 5,
 "irons_spellbooks:dead_king": 5,
 "goety:apostle": 5,
 "bosses_of_mass_destruction:lich": 5,
 "bosses_of_mass_destruction:void_blossom": 6,
 "bosses_of_mass_destruction:obsidilith": 6,
 "iceandfire:fire_dragon": 5,
 "iceandfire:ice_dragon": 6,
 "iceandfire:dread_lich": 6,
 "born_in_chaos_v1:lord_pumpkinhead": 4,
 "born_in_chaos_v1:mother_spider": 3,
 "minecraft:wither": 5,
 "minecraft:ender_dragon": 6,
 "minecraft:elder_guardian": 3
}
const ALD_BOSS_CHANCE = {"twilightforest:knight_phantom": 0.17}

EntityEvents.death(event => {
  const e = event.entity
  const id = String(e.type)
  const tier = ALD_BOSS_TIER[id]
  if (!tier || e.level.isClientSide()) return
  const near = event.source.player || e.level.getNearestPlayer(e.x, e.y, e.z, 48, false)
  if (!near) return
  const chance = ALD_BOSS_CHANCE[id]
  if (chance && Math.random() > chance) return
  const dim = String(e.level.dimension)
  const pos = id == 'minecraft:ender_dragon' ? '0 80 0' : Math.floor(e.x) + ' ' + Math.floor(e.y + 1) + ' ' + Math.floor(e.z)
  event.server.runCommandSilent('execute in ' + dim + ' run loot spawn ' + pos + ' loot aldreth:boss/t' + tier)
})
