// Embers of Aldreth: flight-item loot gates (generated by tools/build_traversal.py).
// Elytra belong to the End: strip them from every loot table except the End's own (catches nested calls from Nether, bounty-bag, vault and bartering tables).
LootJS.modifiers(event => {
  event.addLootTableModifier(/^(?!(minecraft:chests\/end_city_treasure|minecraft:entities\/ender_dragon|lootr:chests\/elytra|bountybags:items\/dragon|tide:chests\/crates\/end|botania:loonium\/minecraft\/end_city|repurposed_structures:chests\/pyramids\/end|repurposed_structures:trapped_chests\/pyramids\/end|repurposed_structures:chests\/shipwrecks\/end\/treasure)$).*/).removeLoot('minecraft:elytra')
})
