// Embers of Aldreth: Warden Sigil recipes (generated by tools/build_sigils.py). Crafting a sigil unlocks its realm (Restricted Portals).
ServerEvents.recipes(event => {
  event.shapeless('aldreth:sigil_of_flame', ["aldreth:ember_shard", "minecraft:flint_and_steel", "minecraft:obsidian", "minecraft:obsidian"]).id('aldreth:sigil/flame')
  event.shapeless('aldreth:sigil_of_root', ["aldreth:ember_shard", "minecraft:diamond", "#minecraft:saplings", "minecraft:moss_block"]).id('aldreth:sigil/root')
  event.shapeless('aldreth:sigil_of_stone', ["aldreth:ember_shard", "minecraft:iron_block", "minecraft:cobbled_deepslate", "minecraft:glow_berries"]).id('aldreth:sigil/stone')
  event.shapeless('aldreth:sigil_of_sky', ["aldreth:ember_shard", "aldreth:ember_shard", "minecraft:glowstone", "minecraft:feather", "twilightforest:naga_scale"]).id('aldreth:sigil/sky')
  event.shapeless('aldreth:sigil_of_dream', ["aldreth:ember_shard", "aldreth:ember_shard", "minecraft:amethyst_shard", "minecraft:diamond", "minecraft:blaze_rod"]).id('aldreth:sigil/dream')
  event.shapeless('aldreth:sigil_of_echo', ["aldreth:ember_shard", "aldreth:ember_shard", "aldreth:ember_shard", "minecraft:echo_shard", "minecraft:sculk_catalyst"]).id('aldreth:sigil/echo')
  event.shapeless('aldreth:sigil_of_the_end', ["aldreth:ember_shard", "aldreth:ember_shard", "aldreth:ember_shard", "aldreth:ember_shard", "minecraft:ender_eye", "minecraft:nether_star"]).id('aldreth:sigil/end')
})
