// Embers of Aldreth: flight guard (generated by tools/build_traversal.py; edit that tool, not this file).
// 1. Aether flyers only function inside the Aether.
// 2. Before the Act III stage 'aldreth_flight', overworld flying mounts can be tamed and ridden on foot, but drop their rider once airborne.
// 3. Flying mounts, elytra and ability flight (tiara, ring, ritual) are fenced out of the Wardens' places: boss arenas, mega-dungeons, fortresses, cities.
// Riders who are dropped get slow falling, so a fence is a lesson, not a death.
const TagKey = Java.loadClass('net.minecraft.tags.TagKey')
const Registries = Java.loadClass('net.minecraft.core.registries.Registries')
const ResourceLocation = Java.loadClass('net.minecraft.resources.ResourceLocation')
const NO_FLIGHT = TagKey.create(Registries.STRUCTURE, new ResourceLocation('aldreth:no_flight'))
const FLYERS = new Set(["iceandfire:hippogryph", "iceandfire:amphithere", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "wyrmroost:canari_wyvern", "wyrmroost:royal_red", "wyrmroost:overworld_drake", "wyrmroost:silver_glider", "wyrmroost:butterfly_leviathan", "wyrmroost:alpine", "alexscaves:subterranodon", "endertrigon:baby_ender_dragon", "goety:haunted_broom", "tameablebeasts:argentavis", "tameablebeasts:quetzalcoatlus", "tameablebeasts:graptera", "tameablebeasts:beetle_drone"])
const AETHER_FLYERS = new Set(["aether:flying_cow", "aether:phyg", "aether:aerwhale", "aether:sheepuff", "aether:moa"])
const FLIGHT_STAGE = 'aldreth_flight'

function aldDrop(p, msg) {
  p.potionEffects.add('minecraft:slow_falling', 160, 0, false, false)
  p.tell(Text.gray(msg))
}

PlayerEvents.tick(event => {
  const p = event.player
  if (p.age % 20 != 0 || p.creative || p.spectator) return
  const mount = p.vehicle
  const gliding = p.fallFlying
  const abilityFlying = p.abilities.flying
  if (!mount && !gliding && !abilityFlying) return
  const mountId = mount ? String(mount.type) : ''
  if (mountId && AETHER_FLYERS.has(mountId)) {
    if (String(p.level.dimension) != 'aether:the_aether') {
      p.stopRiding()
      aldDrop(p, 'These creatures belong to the sky-country; they will not carry you beyond it.')
    }
    return
  }
  const flyMount = mountId && FLYERS.has(mountId)
  if (flyMount && !p.stages.has(FLIGHT_STAGE)) {
    const air = mount.onGround() || mount.isInWater() ? 0 : p.persistentData.getInt('aldFlyAir') + 1
    p.persistentData.putInt('aldFlyAir', air)
    if (air >= 2) {
      p.stopRiding()
      p.persistentData.putInt('aldFlyAir', 0)
      aldDrop(p, 'Your mount will walk with you, but it will not yet trust you with the sky. (Flight opens in Act III.)')
    }
    return
  }
  if (!flyMount && !gliding && !abilityFlying) return
  let start = null
  try { start = p.level.structureManager().getStructureWithPieceAt(p.blockPosition(), NO_FLIGHT) } catch (e) { return }
  if (start && start.isValid()) {
    if (flyMount) p.stopRiding()
    if (gliding) p.stopFallFlying()
    if (abilityFlying) { p.abilities.flying = false; p.onUpdateAbilities() }
    aldDrop(p, 'The old keepers built this place to be climbed, not overflown. Your wings fail you at the door.')
  }
})
