// Embers of Aldreth: flight guard (generated by tools/build_traversal.py; edit that tool, not this file).
// Flying mounts, elytra and wings are fenced out of the Wardens' places: boss arenas, mega-dungeons, fortresses and cities.
// Aether flyers only function inside the Aether.
const TagKey = Java.loadClass('net.minecraft.tags.TagKey')
const Registries = Java.loadClass('net.minecraft.core.registries.Registries')
const ResourceLocation = Java.loadClass('net.minecraft.resources.ResourceLocation')
const NO_FLIGHT = TagKey.create(Registries.STRUCTURE, new ResourceLocation('aldreth:no_flight'))
const FLYERS = new Set(["iceandfire:hippogryph", "iceandfire:amphithere", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "wyrmroost:canari_wyvern", "wyrmroost:royal_red", "wyrmroost:overworld_drake", "wyrmroost:silver_glider", "wyrmroost:butterfly_leviathan", "alexscaves:subterranodon", "endertrigon:baby_ender_dragon"])
const AETHER_FLYERS = new Set(["aether:flying_cow", "aether:phyg", "aether:aerwhale", "aether:sheepuff", "aether:moa"])

PlayerEvents.tick(event => {
  const p = event.player
  if (p.age % 20 != 0 || p.creative || p.spectator) return
  const mount = p.vehicle
  const gliding = p.fallFlying
  if (!mount && !gliding) return
  const mountId = mount ? String(mount.type) : ''
  if (mountId && AETHER_FLYERS.has(mountId) && String(p.level.dimension) != 'aether:the_aether') {
    p.stopRiding()
    p.tell(Text.gray('These creatures belong to the sky-country; they will not carry you beyond it.'))
    return
  }
  const flying = (mountId && FLYERS.has(mountId)) || gliding
  if (!flying) return
  let start = null
  try { start = p.level.structureManager().getStructureWithPieceAt(p.blockPosition(), NO_FLIGHT) } catch (e) { return }
  if (start && start.isValid()) {
    if (mountId && FLYERS.has(mountId)) p.stopRiding()
    if (gliding) p.stopFallFlying()
    p.tell(Text.gray('The old keepers built this place to be climbed, not overflown. Your wings fail you at the door.'))
  }
})
