// Embers of Aldreth: custom items (generated by tools/build_sigils.py from design/custom_items.py).
StartupEvents.registry('item', event => {
  event.create('aldreth:ember_shard').displayName('Ember Shard').rarity('uncommon').glow(true).maxStackSize(64)
  event.create('aldreth:sigil_of_flame').displayName('Sigil of Flame').rarity('rare').glow(true).maxStackSize(1)
  event.create('aldreth:sigil_of_root').displayName('Sigil of Root').rarity('rare').glow(true).maxStackSize(1)
  event.create('aldreth:sigil_of_stone').displayName('Sigil of Stone').rarity('rare').glow(true).maxStackSize(1)
  event.create('aldreth:sigil_of_sky').displayName('Sigil of Sky').rarity('rare').glow(true).maxStackSize(1)
  event.create('aldreth:sigil_of_dream').displayName('Sigil of Dream').rarity('rare').glow(true).maxStackSize(1)
  event.create('aldreth:sigil_of_echo').displayName('Sigil of Echo').rarity('rare').glow(true).maxStackSize(1)
  event.create('aldreth:sigil_of_the_end').displayName('Sigil of the End').rarity('rare').glow(true).maxStackSize(1)
})
