// Embers of Aldreth: sigil tooltips (generated by tools/build_sigils.py).
ItemEvents.tooltip(event => {
  event.add('aldreth:ember_shard', Text.gold('A splinter of the Hollow Crown. Sigils are made from these.'))
  event.add('aldreth:sigil_of_flame', [Text.gray('Unseals the Flame Ward: the Nether.'), Text.darkGray('Crafting this unlocks the portal for you.')])
  event.add('aldreth:sigil_of_root', [Text.gray('Unseals the Root Ward: the Twilight Forest.'), Text.darkGray('Crafting this unlocks the portal for you.')])
  event.add('aldreth:sigil_of_stone', [Text.gray('Unseals the Stone Ward: the Undergarden.'), Text.darkGray('Crafting this unlocks the portal for you.')])
  event.add('aldreth:sigil_of_sky', [Text.gray('Unseals the Sky Ward: the Aether.'), Text.darkGray('Crafting this unlocks the portal for you.')])
  event.add('aldreth:sigil_of_dream', [Text.gray('Unseals the Dream Ward: Everbright and Everdawn.'), Text.darkGray('Crafting this unlocks the portal for you.')])
  event.add('aldreth:sigil_of_echo', [Text.gray('Unseals the Echo Ward: the Otherside.'), Text.darkGray('Crafting this unlocks the portal for you.')])
  event.add('aldreth:sigil_of_the_end', [Text.gray('Unseals the last Ward: the End.'), Text.darkGray('Crafting this unlocks the portal for you.')])
})
