"""Hearth and Home (farming, cooking, fishing, building, animals) and Bounties and Trials."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "tools"))
from questlib import *

CHAPTERS = []

# =============================================================== FARM AND KITCHEN ==================================================
c = Chapter("kitchen", "The Hearth: Farm and Kitchen", "farmersdelight:cooking_pot", "hearth", "A well-fed hero is a dangerous hero. Food gives real, lasting boons.", bg="farming")
c.q("intro", "A Fire and a Pot", "farmersdelight:cooking_pot", ["Meals here are more than hunger: a good stew gives comfort, resistance, speed. The Farmer's Delight family of mods turns a kitchen into a workshop.", "Eat varied food and Spice of Life rewards you with health. Repeat the same meal and it stops mattering."], [item("farmersdelight:cooking_pot")], [xp(25)], shape="diamond", size=1.3)
c.q("knife", "A Good Knife", "farmersdelight:iron_knife", "A knife and a cutting board turn raw ingredients into good ones.", [item("farmersdelight:iron_knife")], [xp(20)], deps=["intro"])
c.q("board", "The Cutting Board", "farmersdelight:cutting_board", "Slice, dice and strip. Cutting is half of cooking.", [item("farmersdelight:cutting_board")], [xp(20)], deps=["knife"])
c.q("onion", "A Garden", "farmersdelight:onion", "Onions, cabbages, tomatoes, rice. Plant, wait, harvest.", [item("farmersdelight:onion", 4)], [xp(25)], deps=["intro"])
c.q("stew", "A Hearty Stew", "farmersdelight:beef_stew", "Beef, vegetables and patience. A good stew heals and satisfies.", [item("farmersdelight:beef_stew")], [xp(40)], deps=["board", "onion"])
c.q("soup", "Chicken Soup", "farmersdelight:chicken_soup", "The simple remedy.", [item("farmersdelight:chicken_soup")], [xp(40)], deps=["stew"], optional=True)
c.q("pie", "Apple Pie", "farmersdelight:apple_pie", "Pastry and fruit. A treat; a reward; a boon.", [item("farmersdelight:apple_pie")], [xp(50)], deps=["stew"], optional=True)
c.q("ham", "Honey-Glazed Ham", "farmersdelight:honey_glazed_ham", "A feast dish. It feeds a table and restores a lot.", [item("farmersdelight:honey_glazed_ham")], [xp(80)], deps=["stew"])
c.q("fish", "Fish Stew", "farmersdelight:fish_stew", "From the water, into the pot.", [item("farmersdelight:fish_stew")], [xp(40)], deps=["stew"], optional=True)
c.q("burger", "Hamburger", "farmersdelight:hamburger", "Humble and filling.", [item("farmersdelight:hamburger")], [xp(40)], deps=["stew"], optional=True)
c.q("dumpling", "Dumplings", "farmersdelight:dumplings", "Small and useful: portable healing.", [item("farmersdelight:dumplings")], [xp(40)], deps=["stew"], optional=True)
c.q("variety", "A Varied Diet", "minecraft:golden_apple", "Eat a dozen different dishes. Variety is its own buff.", [check()], [xp(100), points(1)], deps=["ham"], shape="hexagon")
c.q("feast", "A Feast", "minecraft:cake", "Prepare a feast for friends. In multiplayer, it is a tradition.", [check()], [xp(120)], deps=["variety"], optional=True)
c.q("horse", "Horse Feed", "farmersdelight:horse_feed", "A good meal for a good mount.", [item("farmersdelight:horse_feed")], [xp(50)], deps=["intro"], optional=True)
c.q("dogfood", "Dog Food", "farmersdelight:dog_food", "Feed your dog properly.", [item("farmersdelight:dog_food")], [xp(50)], deps=["intro"], optional=True)
CHAPTERS.append(c)

# =============================================================== FISHING AND FORAGING ===============================================
c = Chapter("fishing", "The Patient Hand: Fishing and Foraging", "aquaculture:iron_fishing_rod", "hearth", "Quiet work for the weary.", bg="fishing")
c.q("intro", "A Rod and a Line", "aquaculture:iron_fishing_rod", ["Fishing is a pastime and an economy: crates, treasure, rare fish, and ingredients for the best meals. Bait and hooks change what you catch."], [item("aquaculture:iron_fishing_rod")], [xp(25)], shape="diamond", size=1.3)
c.q("hook", "A Better Hook", "aquaculture:gold_hook", "Hooks matter: light, heavy, double, gold. Match them to the water.", [item("aquaculture:gold_hook")], [xp(30)], deps=["intro"])
c.q("worm", "A Worm Farm", "aquaculture:worm_farm", "Bait for the patient.", [item("aquaculture:worm_farm")], [xp(30)], deps=["intro"], optional=True)
c.q("box", "A Tackle Box", "aquaculture:tackle_box", "Store your hooks, line and bait.", [item("aquaculture:tackle_box")], [xp(40)], deps=["hook"], optional=True)
c.q("fillet", "Fish Fillets", "aquaculture:fish_fillet_cooked", "Clean, cook and eat.", [item("aquaculture:fish_fillet_cooked")], [xp(30)], deps=["hook"])
c.q("neptunium", "Neptunium", "aquaculture:neptunium_ingot", "A rare metal from the deep sea. Its tools are among the best for fishing and diving.", [item("aquaculture:neptunium_ingot")], [xp(150), cache(3)], deps=["box"], shape="hexagon")
c.q("rod", "The Neptunium Rod", "aquaculture:neptunium_fishing_rod", "The finest rod in the pack.", [item("aquaculture:neptunium_fishing_rod")], [xp(200)], deps=["neptunium"], optional=True)
c.q("forage", "Foraging", "minecraft:sweet_berries", "Berries, mushrooms and herbs: a walk in the woods is also a shopping trip.", [item("minecraft:sweet_berries", 4)], [xp(25)], deps=["intro"], optional=True)
c.q("mushroom", "Mushroom Hunter", "minecraft:red_mushroom", "Some mushrooms heal, some poison. Learn which is which.", [item("minecraft:brown_mushroom", 4)], [xp(25)], deps=["forage"], optional=True)
c.q("master", "A Patient Hand", "minecraft:cod", "A season of fishing and foraging. You have eaten well.", [check()], [xp(150), points(1)], deps=["fillet", "forage"], shape="hexagon")
CHAPTERS.append(c)

# =============================================================== BUILDING ===========================================================
c = Chapter("building", "Home, Hearth and Hall", "minecraft:oak_door", "hearth", "A base is a story you tell with blocks.", bg="building")
c.q("intro", "A Place to Come Home To", "minecraft:red_bed", ["The pack has a huge decoration library: furniture, lighting, windows, paths, roofs, paintings and more. Build a house you are proud of; the quest book will not tell you how."], [check()], [xp(20)], shape="diamond", size=1.3)
c.q("furniture", "Furniture", "minecraft:oak_stairs", "Chairs, tables, couches, shelves. Handcrafted and Macaw's furniture are everywhere.", [check()], [xp(30)], deps=["intro"])
c.q("lamp", "Light and Lamps", "minecraft:lantern", "Torches, lanterns, sconces. Good light is the best decoration.", [item("minecraft:lantern", 4)], [xp(30)], deps=["intro"])
c.q("path", "Paths and Roofs", "minecraft:cobblestone_stairs", "Macaw's and Twigs give you every roof and path you can imagine.", [check()], [xp(30)], deps=["intro"])
c.q("storage", "Storage", "minecraft:chest", "Sophisticated Backpacks and Storage replace a wall of chests. Carry a backpack.", [item("minecraft:chest", 4)], [xp(40)], deps=["intro"])
c.q("workshop", "A Workshop", "minecraft:smithing_table", "A smithing table, anvil, grindstone and enchanting table in one room is a workshop.", [item("minecraft:smithing_table"), item("minecraft:anvil")], [xp(40)], deps=["storage"])
c.q("garden", "A Garden", "minecraft:flower_pot", "Plants make a house a home.", [item("minecraft:flower_pot", 2)], [xp(30)], deps=["lamp"], optional=True)
c.q("library", "A Library", "minecraft:bookshelf", "Shelves, tomes, an enchanting table: the nerve centre of a caster's house.", [item("minecraft:bookshelf", 12)], [xp(50)], deps=["workshop"], optional=True)
c.q("stable", "A Stable", "minecraft:hay_block", "Keep your mounts safe, fed and happy.", [item("minecraft:hay_block", 4)], [xp(40)], deps=["intro"])
c.q("claim", "Claim Your Land", "minecraft:white_banner", "Claim chunks with FTB Chunks or Open Parties and Claims. In multiplayer it is the difference between a home and a ruin.", [check()], [xp(40)], deps=["intro"])
c.q("castle", "Your Own Keep", "minecraft:stone_bricks", "A castle of your own. Walls, towers and a gate.", [check()], [xp(150), points(1)], deps=["workshop", "stable"], shape="hexagon", size=1.3)
c.q("paint", "A Gallery", "minecraft:painting", "Paintings and posters give a house its personality.", [item("minecraft:painting", 3)], [xp(30)], deps=["furniture"], optional=True)
c.q("sign", "A Sign Post", "minecraft:oak_sign", "Mark your territory.", [item("minecraft:oak_sign", 2)], [xp(20)], deps=["intro"], optional=True)
CHAPTERS.append(c)

# =============================================================== ANIMALS ============================================================
c = Chapter("animals", "Beasts, Bonds and Breeding", "minecraft:lead", "hearth", "A world of creatures worth knowing.", bg="animals")
c.q("intro", "A Beast of Your Own", "minecraft:lead", ["The pack is full of animals: wolves, cats, parrots, elephants, kangaroos, raptors, dragons. Some tame, some breed, some are just friends."], [item("minecraft:lead")], [xp(20)], shape="diamond", size=1.3)
c.q("wolf", "A Dog", "minecraft:bone", "A tamed wolf is a loyal companion. Feed it well.", [adv("minecraft:husbandry/tame_an_animal")], [xp(40)], deps=["intro"])
c.q("cat", "A Cat", "minecraft:cod", "Cats scare creepers. That is worth keeping one.", [item("minecraft:cod")], [xp(30)], deps=["intro"], optional=True)
c.q("breed", "Breeding", "minecraft:wheat", "Breed two animals and get a third. The basics of ranching.", [adv("minecraft:husbandry/breed_an_animal")], [xp(40)], deps=["intro"])
c.q("bees", "Beekeeping", "minecraft:honeycomb", "Bees pollinate, honey sweetens, and wax lasts.", [adv("minecraft:husbandry/safely_harvest_honey")], [xp(50)], deps=["breed"], optional=True)
c.q("wildlife", "Alex's Menagerie", "alexsmobs:vine_lasso", "A large menagerie of weird animals; some tamable, some rideable, some just alarming. Catalogue them in the Animal Dictionary.", [check()], [xp(60)], deps=["intro"], optional=True)
c.q("egg", "A Strange Egg", "minecraft:egg", "Eggs, nests and incubators: some beasts hatch from eggs.", [item("minecraft:egg", 2)], [xp(30)], deps=["breed"], optional=True)
c.q("flute", "A Dragon's Companion", "iceandfire:dragon_flute", "A dragon is not a pet or a mount; it is a partner with its own life.", [adv("iceandfire:iceandfire/dragon_flute")], [xp(150)], deps=["wolf"], optional=True)
c.q("zoo", "A Menagerie", "minecraft:lead", "Keep five different species in your care. You have a zoo.", [check()], [xp(150), points(1)], deps=["wolf", "breed"], shape="hexagon")
CHAPTERS.append(c)

# =============================================================== BOUNTIES AND TRIALS ================================================
c = Chapter("bounties", "Bounties and Trials", "minecraft:iron_axe", "trials", "Hunt by contract. Prove yourself on purpose.", bg="bounties")
c.q("intro", "The Bounty Board", "minecraft:oak_sign", ["Bounties are small contracts: kill this, bring that, survive these. Some pay in coin, some in rare materials, some in a title.", "Each one is optional. Together they are a long path through the game's hostile corners."], [check()], [xp(20)], shape="diamond", size=1.3)
c.q("undead", "Rotting Dead", "minecraft:rotten_flesh", "Clear the undead: twenty zombies, ten skeletons.", [kill("minecraft:zombie", 20), kill("minecraft:skeleton", 10)], [xp(60), cache(1)], deps=["intro"])
c.q("spiders", "Eight-Legged Menace", "minecraft:spider_eye", "Spiders and cave spiders. They are in the dark.", [kill("minecraft:spider", 15), kill("minecraft:cave_spider", 10)], [xp(60), cache(1)], deps=["intro"])
c.q("creepers", "Fuses", "minecraft:gunpowder", "Creepers: kill them from a distance.", [kill("minecraft:creeper", 10)], [xp(50), cache(1)], deps=["intro"])
c.q("witches", "Brewmasters", "minecraft:potion", "Witches cook trouble.", [kill("minecraft:witch", 5)], [xp(80), cache(2)], deps=["undead"])
c.q("illagers", "A Raid", "minecraft:white_banner", "Defend a village from a raid. Hero of the Village is the prize.", [kill("minecraft:vindicator", 10), kill("minecraft:evoker", 3)], [xp(150), cache(2)], deps=["witches"])
c.q("blazes", "Blaze Hunt", "minecraft:blaze_rod", "Blazes in the fortress. Bring fire resistance.", [kill("minecraft:blaze", 12)], [xp(100), cache(2)], deps=["illagers"])
c.q("wither_skel", "Wither Skeletons", "minecraft:wither_skeleton_skull", "A skull is a bounty. Three skulls are a boss.", [kill("minecraft:wither_skeleton", 8)], [xp(150), cache(3)], deps=["blazes"])
c.q("guardians", "Sea Guardians", "minecraft:prismarine_shard", "Guardians in the monument. Be waterborne.", [kill("minecraft:guardian", 10)], [xp(120), cache(3)], deps=["illagers"])
c.q("endermen", "Enderman Hunt", "minecraft:ender_pearl", "Pearls are valuable and endermen are rude.", [kill("minecraft:enderman", 15)], [xp(150), cache(3)], deps=["wither_skel"])
c.q("shulker", "Shulker Hunt", "minecraft:shulker_shell", "Shulkers in the End city.", [kill("minecraft:shulker", 5)], [xp(200), cache(4)], deps=["endermen"])
c.q("raptor", "The Raptor Pack", "minecraft:feather", "Umvuthana raptors, in a pack.", [kill("mowziesmobs:umvuthana_raptor", 6)], [xp(150), cache(3)], deps=["wither_skel"], optional=True)
c.q("dreadful", "Nightmare Hunt", "minecraft:soul_lantern", "Night creatures from Born in Chaos.", [kill("born_in_chaos_v1:nightmare_stalker", 3)], [xp(180), cache(3)], deps=["wither_skel"], optional=True)
c.q("prehistoric", "Cave Predators", "alexscaves:heavy_bone", "Raptors, rexes, and other things that bite.", [kill("alexscaves:vallumraptor", 5), kill("alexscaves:tremorsaurus", 1)], [xp(250), cache(4)], deps=["wither_skel"], optional=True)
c.q("dragonslayer", "Drake Hunt", "iceandfire:dragon_skull_fire", "The last bounty on the board: a dragon. It will not be easy.", [kill("iceandfire:fire_dragon")], [xp(500), points(1), cache(5)], deps=["shulker", "prehistoric"], shape="hexagon")
c.q("trial1", "Trial of Blades", "minecraft:iron_sword", "Defeat fifty monsters without dying. Count them: the Compendium will not.", [check()], [xp(150)], deps=["undead"], optional=True)
c.q("trial2", "Trial of Silence", "minecraft:feather", "Clear a dungeon without a single arrow or spell. Only blades.", [check()], [xp(300), points(1)], deps=["trial1"], optional=True)
c.q("trial3", "Trial of Hunger", "minecraft:bread", "Complete a boss with no food and no potions. You do not need to.", [check()], [xp(500), points(1)], deps=["trial2"], optional=True)
c.q("trial4", "Trial of One", "minecraft:totem_of_undying", "Beat a great structure alone, without any pets or summons.", [check()], [xp(800), points(2)], deps=["trial3"], optional=True, shape="hexagon")
CHAPTERS.append(c)
