#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 06 23:21:53 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9.3.zip
enableShaders=false
