
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Message that displays when Teleport is blocked
	blockedmessage = "The way is sealed. Craft a %item% to open the %dim%."
	#Title for the Advancements
	craftedmessage = "%dim% Unsealed"
	#Description for the Advancements
	description = "Craft a %item%"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "aldreth:sigil_of_flame,aldreth:sigil_of_root,aldreth:sigil_of_stone,aldreth:sigil_of_sky,aldreth:sigil_of_dream,aldreth:sigil_of_dream,aldreth:sigil_of_echo,aldreth:sigil_of_the_end"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether,twilightforest:twilight_forest,undergarden:undergarden,aether:the_aether,blue_skies:everbright,blue_skies:everdawn,deeperdarker:otherside,minecraft:the_end"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether,Twilight Forest,Undergarden,Aether,Everbright,Everdawn,Otherside,End"

