"""Generate flight-guard data: entity tags (aldreth:flying_mounts, aldreth:aether_flyers) and structure tag (aldreth:no_flight) from the registry
snapshot, plus kubejs/server_scripts/traversal_flight_guard.js. Usage: python tools/build_traversal.py"""
import json, os, re

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
reg = json.load(open(os.path.join(ROOT, "pack", "registries_snapshot.json"), encoding="utf-8"))
ENT, STR = set(reg["entity_type"]), set(reg["structure"])
pack = os.path.join(ROOT, "config", "paxi", "datapacks", "aldreth_core", "data", "aldreth", "tags")

FLY = ["iceandfire:hippogryph", "iceandfire:amphithere", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "wyrmroost:canari_wyvern",
       "wyrmroost:royal_red", "wyrmroost:overworld_drake", "wyrmroost:silver_glider", "wyrmroost:butterfly_leviathan", "wyrmroost:alpine", "alexscaves:subterranodon", "endertrigon:baby_ender_dragon",
       "goety:haunted_broom", "tameablebeasts:argentavis", "tameablebeasts:quetzalcoatlus", "tameablebeasts:graptera", "tameablebeasts:beetle_drone"]
AETHER = ["aether:flying_cow", "aether:phyg", "aether:aerwhale", "aether:sheepuff", "aether:moa"]
FLY = [e for e in FLY if e in ENT]
AETHER = [e for e in AETHER if e in ENT]
os.makedirs(os.path.join(pack, "entity_types"), exist_ok=True)
json.dump({"replace": True, "values": FLY}, open(os.path.join(pack, "entity_types", "flying_mounts.json"), "w"), indent=1)
json.dump({"replace": True, "values": AETHER}, open(os.path.join(pack, "entity_types", "aether_flyers.json"), "w"), indent=1)

# loot tables allowed to give elytra: the End's own (everything else, including nested calls from Nether/bounty/vault tables, is stripped)
END_ELYTRA = ["minecraft:chests/end_city_treasure", "minecraft:entities/ender_dragon", "lootr:chests/elytra", "bountybags:items/dragon", "tide:chests/crates/end",
              "botania:loonium/minecraft/end_city", "repurposed_structures:chests/pyramids/end", "repurposed_structures:trapped_chests/pyramids/end",
              "repurposed_structures:chests/shipwrecks/end/treasure"]
# fenced structures: boss arenas, mega-dungeons, fortresses and Warden cities
NS_ALL = ("cataclysm", "prodigium_dungeons", "born_in_chaos_v1", "bosses_of_mass_destruction", "dungeons_enhanced", "dungeons_plus", "goety", "blue_skies", "aether", "aether_redux",
          "ancient_aether", "deep_aether", "irons_spellbooks", "block_factorys_bosses", "mes", "mns", "mss", "mvs", "ati_structures")
EXTRA = [s for s in STR if re.match(r"^(dungeons_arise:(keep_kayra|shiraz_palace|coliseum|typhon|heavenly_[a-z]+|bandit_towers|bandit_village|illager_fort|mechanical_nest|plague_asylum|monastery|thornborn_towers|foundry|scorched_mines|undead_pirate_ship)|"
                                r"twilightforest:(lich_tower|hydra_lair|final_castle|dark_tower|labyrinth|aurora_palace|knight_stronghold|naga_courtyard|yeti_cave|troll_cave)|"
                                r"minecraft:(stronghold|ancient_city|bastion_remnant|fortress|end_city|mansion|monument)|betterstrongholds:.*|betteroceanmonuments:.*)$", s)]
fenced = sorted(set(EXTRA) | {s for s in STR if s.split(":")[0] in NS_ALL})
os.makedirs(os.path.join(pack, "worldgen", "structure"), exist_ok=True)
json.dump({"replace": True, "values": fenced}, open(os.path.join(pack, "worldgen", "structure", "no_flight.json"), "w"), indent=1)

js = """// Embers of Aldreth: flight guard (generated by tools/build_traversal.py; edit that tool, not this file).
// 1. Aether flyers only function inside the Aether.
// 2. Before the Act III stage 'aldreth_flight', overworld flying mounts can be tamed and ridden on foot, but drop their rider once airborne.
// 3. Flying mounts, elytra and ability flight (tiara, ring, ritual) are fenced out of the Wardens' places: boss arenas, mega-dungeons, fortresses, cities.
// Riders who are dropped get slow falling, so a fence is a lesson, not a death.
const TagKey = Java.loadClass('net.minecraft.tags.TagKey')
const Registries = Java.loadClass('net.minecraft.core.registries.Registries')
const ResourceLocation = Java.loadClass('net.minecraft.resources.ResourceLocation')
const NO_FLIGHT = TagKey.create(Registries.STRUCTURE, new ResourceLocation('aldreth:no_flight'))
const FLYERS = new Set(%s)
const AETHER_FLYERS = new Set(%s)
const FLIGHT_STAGE = 'aldreth_flight'

function aldDrop(p, msg) {
  p.potionEffects.add('minecraft:slow_falling', 160, 0, false, false)
  p.tell(Text.gray(msg))
}

PlayerEvents.tick(event => {
  const p = event.player
  if (p.age %% 20 != 0 || p.creative || p.spectator) return
  const mount = p.vehicle
  const gliding = p.fallFlying
  const abilityFlying = p.abilities.flying
  if (!mount && !gliding && !abilityFlying) return
  const mountId = mount ? String(mount.type) : ''
  if (mountId && AETHER_FLYERS.has(mountId)) {
    if (String(p.level.dimension) != 'aether:the_aether') {
      p.stopRiding()
      aldDrop(p, 'These creatures belong to the sky-country; they will not carry you beyond it.')
    }
    return
  }
  const flyMount = mountId && FLYERS.has(mountId)
  if (flyMount && !p.stages.has(FLIGHT_STAGE)) {
    const air = mount.onGround() || mount.isInWater() ? 0 : p.persistentData.getInt('aldFlyAir') + 1
    p.persistentData.putInt('aldFlyAir', air)
    if (air >= 2) {
      p.stopRiding()
      p.persistentData.putInt('aldFlyAir', 0)
      aldDrop(p, 'Your mount will walk with you, but it will not yet trust you with the sky. (Flight opens in Act III.)')
    }
    return
  }
  if (!flyMount && !gliding && !abilityFlying) return
  let start = null
  try { start = p.level.structureManager().getStructureWithPieceAt(p.blockPosition(), NO_FLIGHT) } catch (e) { return }
  if (start && start.isValid()) {
    if (flyMount) p.stopRiding()
    if (gliding) p.stopFallFlying()
    if (abilityFlying) { p.abilities.flying = false; p.onUpdateAbilities() }
    aldDrop(p, 'The old keepers built this place to be climbed, not overflown. Your wings fail you at the door.')
  }
})
""" % (json.dumps(FLY), json.dumps(AETHER))
loot = """// Embers of Aldreth: flight-item loot gates (generated by tools/build_traversal.py).
// Elytra belong to the End: strip them from every loot table except the End's own (catches nested calls from Nether, bounty-bag, vault and bartering tables).
LootJS.modifiers(event => {
  event.addLootTableModifier(/^(?!(%s)$).*/).removeLoot('minecraft:elytra')
})
""" % "|".join(re.escape(t).replace("/", r"\/") for t in END_ELYTRA)
open(os.path.join(ROOT, "kubejs", "server_scripts", "progression_loot_gates.js"), "w", encoding="utf-8").write(loot)
os.makedirs(os.path.join(ROOT, "kubejs", "server_scripts"), exist_ok=True)
open(os.path.join(ROOT, "kubejs", "server_scripts", "traversal_flight_guard.js"), "w", encoding="utf-8").write(js)
print("flying mounts:", len(FLY), "aether flyers:", len(AETHER), "fenced structures:", len(fenced))
