"""Generate flight-guard data: entity tags (aldreth:flying_mounts, aldreth:aether_flyers) and structure tag (aldreth:no_flight) from the registry
snapshot, plus kubejs/server_scripts/traversal_flight_guard.js. Usage: python tools/build_traversal.py"""
import json, os, re

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
reg = json.load(open(os.path.join(ROOT, "pack", "registries_snapshot.json"), encoding="utf-8"))
ENT, STR = set(reg["entity_type"]), set(reg["structure"])
pack = os.path.join(ROOT, "config", "paxi", "datapacks", "aldreth_core", "data", "aldreth", "tags")

FLY = ["iceandfire:hippogryph", "iceandfire:amphithere", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "wyrmroost:canari_wyvern",
       "wyrmroost:royal_red", "wyrmroost:overworld_drake", "wyrmroost:silver_glider", "wyrmroost:butterfly_leviathan", "alexscaves:subterranodon", "endertrigon:baby_ender_dragon"]
AETHER = ["aether:flying_cow", "aether:phyg", "aether:aerwhale", "aether:sheepuff", "aether:moa"]
FLY = [e for e in FLY if e in ENT]
AETHER = [e for e in AETHER if e in ENT]
os.makedirs(os.path.join(pack, "entity_types"), exist_ok=True)
json.dump({"replace": True, "values": FLY}, open(os.path.join(pack, "entity_types", "flying_mounts.json"), "w"), indent=1)
json.dump({"replace": True, "values": AETHER}, open(os.path.join(pack, "entity_types", "aether_flyers.json"), "w"), indent=1)

# fenced structures: boss arenas, mega-dungeons, fortresses and Warden cities
NS_ALL = ("cataclysm", "prodigium_dungeons", "born_in_chaos_v1", "bosses_of_mass_destruction", "dungeons_enhanced", "dungeons_plus", "goety", "blue_skies", "aether", "aether_redux",
          "ancient_aether", "deep_aether", "irons_spellbooks", "block_factorys_bosses", "mes", "mns", "mss", "mvs", "ati_structures")
EXTRA = [s for s in STR if re.match(r"^(dungeons_arise:(keep_kayra|shiraz_palace|coliseum|typhon|heavenly_[a-z]+|bandit_towers|bandit_village|illager_fort|mechanical_nest|plague_asylum|monastery|thornborn_towers|foundry|scorched_mines|undead_pirate_ship)|"
                                r"twilightforest:(lich_tower|hydra_lair|final_castle|dark_tower|labyrinth|aurora_palace|knight_stronghold|naga_courtyard|yeti_cave|troll_cave)|"
                                r"minecraft:(stronghold|ancient_city|bastion_remnant|fortress|end_city|mansion|monument)|betterstrongholds:.*|betteroceanmonuments:.*)$", s)]
fenced = sorted(set(EXTRA) | {s for s in STR if s.split(":")[0] in NS_ALL})
os.makedirs(os.path.join(pack, "worldgen", "structure"), exist_ok=True)
json.dump({"replace": True, "values": fenced}, open(os.path.join(pack, "worldgen", "structure", "no_flight.json"), "w"), indent=1)

js = """// Embers of Aldreth: flight guard (generated by tools/build_traversal.py; edit that tool, not this file).
// Flying mounts, elytra and wings are fenced out of the Wardens' places: boss arenas, mega-dungeons, fortresses and cities.
// Aether flyers only function inside the Aether.
const TagKey = Java.loadClass('net.minecraft.tags.TagKey')
const Registries = Java.loadClass('net.minecraft.core.registries.Registries')
const ResourceLocation = Java.loadClass('net.minecraft.resources.ResourceLocation')
const NO_FLIGHT = TagKey.create(Registries.STRUCTURE, new ResourceLocation('aldreth:no_flight'))
const FLYERS = new Set(%s)
const AETHER_FLYERS = new Set(%s)

PlayerEvents.tick(event => {
  const p = event.player
  if (p.age %% 20 != 0 || p.creative || p.spectator) return
  const mount = p.vehicle
  const gliding = p.fallFlying
  if (!mount && !gliding) return
  const mountId = mount ? String(mount.type) : ''
  if (mountId && AETHER_FLYERS.has(mountId) && String(p.level.dimension) != 'aether:the_aether') {
    p.stopRiding()
    p.tell(Text.gray('These creatures belong to the sky-country; they will not carry you beyond it.'))
    return
  }
  const flying = (mountId && FLYERS.has(mountId)) || gliding
  if (!flying) return
  let start = null
  try { start = p.level.structureManager().getStructureWithPieceAt(p.blockPosition(), NO_FLIGHT) } catch (e) { return }
  if (start && start.isValid()) {
    if (mountId && FLYERS.has(mountId)) p.stopRiding()
    if (gliding) p.stopFallFlying()
    p.tell(Text.gray('The old keepers built this place to be climbed, not overflown. Your wings fail you at the door.'))
  }
})
""" % (json.dumps(FLY), json.dumps(AETHER))
os.makedirs(os.path.join(ROOT, "kubejs", "server_scripts"), exist_ok=True)
open(os.path.join(ROOT, "kubejs", "server_scripts", "traversal_flight_guard.js"), "w", encoding="utf-8").write(js)
print("flying mounts:", len(FLY), "aether flyers:", len(AETHER), "fenced structures:", len(fenced))
