"""Assemble the Aldreth quest book from design/quests/*.py into config/ftbquests/quests (+ docs/QUESTS.md), validating every ID.
Usage: python tools/build_quests.py [--no-art]"""
import glob, importlib.util, json, os, shutil, sys, collections

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from questlib import *   # noqa

reg = json.load(open(os.path.join(ROOT, "pack", "registries_snapshot.json"), encoding="utf-8"))
GROUPS = [("story", "The Embers of Aldreth"), ("craft", "Arms and Arcana"), ("road", "The Wide Road"), ("hearth", "Hearth and Home"), ("trials", "Bounties and Trials")]
group_ids = {k: hid("group", k) for k, _ in GROUPS}

chapters = []
for f in sorted(glob.glob(os.path.join(ROOT, "design", "quests", "*.py"))):
    spec = importlib.util.spec_from_file_location(os.path.basename(f)[:-3], f)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    chapters += mod.CHAPTERS

qdir = os.path.join(ROOT, "config", "ftbquests", "quests")
cdir = os.path.join(qdir, "chapters")
shutil.rmtree(cdir, ignore_errors=True)
os.makedirs(cdir, exist_ok=True)
errors = []
allkeys = {(c.key, k) for c in chapters for k in c.keys}
for c in chapters:
    for qd in c.quests:
        for d in qd["deps"]:
            if "." in d and tuple(d.split(".")) not in allkeys:
                errors.append("%s/%s: unknown cross-chapter dep %s" % (c.key, qd["key"], d))
seen = set()
total = 0
for idx, ch in enumerate(chapters):
    if ch.key in seen:
        errors.append("duplicate chapter " + ch.key)
    seen.add(ch.key)
    layout(ch)
    validate(ch, reg, errors)
    xs = [qd["x"] for qd in ch.quests]
    ys = [qd["y"] for qd in ch.quests]
    cx, cy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
    w = max(30.0, (max(xs) - min(xs)) + 14)
    h = round(w * 9 / 16, 2)
    image = (round(cx - w / 2, 2), round(cy - h / 2, 2), w, h, '"aldreth:textures/quests/%s.png"' % ch.bg) if ch.bg else None
    open(os.path.join(cdir, "%02d_%s.snbt" % (idx, ch.key)), "w", encoding="utf-8").write(chapter_snbt(ch, group_ids, idx, image))
    total += len(ch.quests)

groups = ["{\n\t\t\tid: \"%s\"\n\t\t\ttitle: %s\n\t\t\torder_index: %d\n\t\t}" % (group_ids[k], q(t), i) for i, (k, t) in enumerate(GROUPS)]
open(os.path.join(qdir, "chapter_groups.snbt"), "w", encoding="utf-8").write("{\n\tchapter_groups: [" + ", ".join(groups) + "]\n}\n")
open(os.path.join(qdir, "data.snbt"), "w", encoding="utf-8").write(
    '{\n\ttitle: "Embers of Aldreth"\n\tversion: 13\n\tdefault_consume_items: false\n\tdefault_reward_team: false\n\tdefault_autoclaim_rewards: "disabled"\n'
    '\tprogression_mode: "flexible"\n\tpause_game: false\n\tshow_lock_icons: true\n\tgrid_scale: 0.5d\n\tdrop_loot_crates: false\n}\n')

# docs
L = ["# Quests: the campaign of Embers of Aldreth", "", "_Generated by `tools/build_quests.py` from `design/quests/*.py`. Do not edit by hand._", "",
     "**%d chapters, %d quests** in %d groups. Every item/entity/structure/biome/dimension/advancement id is validated against the registry snapshot." % (len(chapters), total, len(GROUPS)), ""]
tc = collections.Counter(t["type"] for ch in chapters for qd in ch.quests for t in qd["tasks"])
rc = collections.Counter(r["type"] for ch in chapters for qd in ch.quests for r in qd["rewards"])
pts = sum(int(r["command"].split()[-1]) for ch in chapters for qd in ch.quests for r in qd["rewards"] if r["type"] == "command" and "skilltree points" in r["command"])
L += ["Task mix: " + ", ".join("%s %d" % kv for kv in tc.most_common()), "", "Reward mix: " + ", ".join("%s %d" % kv for kv in rc.most_common()), "", "Skill points granted by quests: **%d** (on top of the XP-purchased points; see SKILL_TREE.md)." % pts, ""]
for gk, gt in GROUPS:
    L += ["## %s" % gt, ""]
    for ch in chapters:
        if ch.group != gk:
            continue
        L += ["### %s (%d quests)" % (ch.title, len(ch.quests)), "", "_%s_" % ch.subtitle, ""]
        for qd in ch.quests:
            tk = ", ".join("%s%s" % (t["type"], (":" + str(t.get("item") or t.get("entity") or t.get("structure") or t.get("dim") or t.get("biome") or t.get("advancement"))) if t["type"] != "checkmark" else "") for t in qd["tasks"])
            L.append("- **%s**%s: %s" % (qd["title"], " (optional)" if qd["optional"] else "", tk))
        L.append("")
open(os.path.join(ROOT, "docs", "QUESTS.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print("chapters:", len(chapters), "quests:", total, "| errors:", len(errors))
for e in errors[:60]:
    print("ERR", e)
sys.exit(1 if errors else 0)
