"""Realm gating: Ember Shards + Warden Sigils. Generates 16x16 item textures, the KubeJS item registry (startup), shapeless recipes (server),
English names/lore, and config/restrictedportals-common.toml (crafting a sigil unlocks its realm's portal for that player).
Source of truth: design/custom_items.py. Usage: python tools/build_sigils.py"""
import json, math, os, sys
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(ROOT, "design"))
from custom_items import EMBER_SHARD, SIGILS, ITEMS  # noqa: E402

TEX = os.path.join(ROOT, "kubejs", "assets", "aldreth", "textures", "item")
os.makedirs(TEX, exist_ok=True)


def shard_png(path):
    im = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    px = im.load()
    # a slanted crystal: diamond silhouette, hot core, dark rim
    for y in range(16):
        for x in range(16):
            u, v = (x - 7.5) / 3.6, (y - 7.5) / 7.2
            r = abs(u + v * 0.35) + abs(v)
            if r <= 1.0:
                k = 1 - r
                if r > 0.82:
                    c = (90, 24, 8)
                else:
                    c = (int(255), int(120 + 120 * k), int(40 + 150 * k * k))
                px[x, y] = c + (255,)
    for (x, y) in ((7, 4), (8, 5), (7, 6)):
        px[x, y] = (255, 250, 220, 255)
    im.save(path)


def sigil_png(path, col, seed):
    im = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    px = im.load()
    for y in range(16):
        for x in range(16):
            d = math.hypot(x - 7.5, y - 7.5)
            if d <= 7.4:
                if d > 6.2:
                    px[x, y] = (70, 50, 30, 255)          # bronze rim
                elif d > 5.4:
                    px[x, y] = (196, 150, 80, 255)
                else:
                    t = d / 5.4
                    px[x, y] = (int(40 + 30 * t), int(28 + 20 * t), int(48 + 30 * t), 255)   # dark stone face
    # rune: a per-realm glyph in the realm color
    pts = {0: [(7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (7, 11), (5, 5), (9, 5), (4, 6), (10, 6)],
           1: [(7, 3), (7, 4), (6, 5), (8, 5), (5, 6), (9, 6), (7, 6), (7, 7), (7, 8), (7, 9), (5, 10), (9, 10), (6, 10), (8, 10), (7, 11)],
           2: [(4, 7), (5, 7), (6, 7), (7, 7), (8, 7), (9, 7), (10, 7), (7, 4), (7, 5), (7, 6), (7, 8), (7, 9), (7, 10), (5, 5), (9, 9)],
           3: [(5, 4), (6, 5), (7, 6), (8, 7), (9, 8), (10, 9), (9, 4), (8, 5), (6, 7), (5, 8), (4, 9), (7, 10), (7, 11)],
           4: [(7, 3), (8, 4), (9, 5), (10, 6), (9, 7), (8, 8), (7, 9), (6, 8), (5, 7), (4, 6), (5, 5), (6, 4), (7, 6), (7, 11)],
           5: [(4, 5), (5, 6), (6, 7), (7, 8), (8, 7), (9, 6), (10, 5), (4, 9), (5, 10), (6, 11), (7, 10), (8, 11), (9, 10), (10, 9)],
           6: [(7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (7, 11), (4, 7), (5, 7), (6, 7), (8, 7), (9, 7), (10, 7), (5, 5), (9, 5), (5, 9), (9, 9)]}[seed % 7]
    for x, y in pts:
        px[x, y] = col + (255,)
    im.save(path)


shard_png(os.path.join(TEX, EMBER_SHARD.split(":")[1] + ".png"))
for i, (k, (iid, name, dims, ing, col, lore)) in enumerate(SIGILS.items()):
    sigil_png(os.path.join(TEX, iid.split(":")[1] + ".png"), col, i)

# ---- KubeJS: registry (startup), recipes (server), lang (assets)
reg = ["// Embers of Aldreth: custom items (generated by tools/build_sigils.py from design/custom_items.py).", "StartupEvents.registry('item', event => {",
       "  event.create('%s').displayName('Ember Shard').rarity('uncommon').glow(true).maxStackSize(64)" % EMBER_SHARD]
for k, (iid, name, dims, ing, col, lore) in SIGILS.items():
    reg.append("  event.create('%s').displayName('%s').rarity('rare').glow(true).maxStackSize(1)" % (iid, name))
reg.append("})")
os.makedirs(os.path.join(ROOT, "kubejs", "startup_scripts"), exist_ok=True)
open(os.path.join(ROOT, "kubejs", "startup_scripts", "aldreth_items.js"), "w", encoding="utf-8").write("\n".join(reg) + "\n")

rec = ["// Embers of Aldreth: Warden Sigil recipes (generated by tools/build_sigils.py). Crafting a sigil unlocks its realm (Restricted Portals).",
       "ServerEvents.recipes(event => {"]
for k, (iid, name, dims, ing, col, lore) in SIGILS.items():
    rec.append("  event.shapeless('%s', %s).id('aldreth:sigil/%s')" % (iid, json.dumps(ing), k))
rec.append("})")
open(os.path.join(ROOT, "kubejs", "server_scripts", "sigil_recipes.js"), "w", encoding="utf-8").write("\n".join(rec) + "\n")

tip = ["// Embers of Aldreth: sigil tooltips (generated by tools/build_sigils.py).", "ItemEvents.tooltip(event => {",
       "  event.add('%s', Text.gold('A splinter of the Hollow Crown. Sigils are made from these.'))" % EMBER_SHARD]
for k, (iid, name, dims, ing, col, lore) in SIGILS.items():
    tip.append("  event.add('%s', [Text.gray('%s'), Text.darkGray('Crafting this unlocks the portal for you.')])" % (iid, lore.replace("'", "\'")))
tip.append("})")
os.makedirs(os.path.join(ROOT, "kubejs", "client_scripts"), exist_ok=True)
open(os.path.join(ROOT, "kubejs", "client_scripts", "sigil_tooltips.js"), "w", encoding="utf-8").write("\n".join(tip) + "\n")

# ---- Restricted Portals: one craft item per dimension (sigils for Dream unlock both Blue Skies worlds)
craft, dimids, dimnames = [], [], []
NAMES = {"minecraft:the_nether": "Nether", "twilightforest:twilight_forest": "Twilight Forest", "undergarden:undergarden": "Undergarden", "aether:the_aether": "Aether",
         "blue_skies:everbright": "Everbright", "blue_skies:everdawn": "Everdawn", "deeperdarker:otherside": "Otherside", "minecraft:the_end": "End"}
for k, (iid, name, dims, ing, col, lore) in SIGILS.items():
    for d in dims:
        craft.append(iid); dimids.append(d); dimnames.append(NAMES[d])
toml = """[options]
\t#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
\tpreventdeath = true
\t#Message that displays when Teleport is blocked
\tblockedmessage = "The way is sealed. Craft a %%item%% to open the %%dim%%."
\t#Title for the Advancements
\tcraftedmessage = "%%dim%% Unsealed"
\t#Description for the Advancements
\tdescription = "Craft a %%item%%"
\t#Comma seperated list of items that when crafted unlock the corresponding dimension
\tcraftitems = "%s"
\t#Comma seperated list of Dimension Resource Names
\tdimresname = "%s"
\t#Comma seperated list of Dimension Display Names
\tdimnames = "%s"
""" % (",".join(craft), ",".join(dimids), ",".join(dimnames))
open(os.path.join(ROOT, "config", "restrictedportals-common.toml"), "w", encoding="utf-8").write(toml.replace("%%", "%"))
print("items:", len(ITEMS), "| sigil recipes:", len(SIGILS), "| gated dims:", len(dimids))
