"""Aldreth quest engine: DSL -> FTB Quests (2001.4.x) SNBT with dependency-based layout and registry validation.

Usage in design/quests/*.py:
    from questlib import *
    CH = Chapter("prologue", "The Ember Wakes", icon="minecraft:blaze_powder", group="story", subtitle="...", bg="prologue")
    CH.q("spark", "A Spark in the Ash", "minecraft:flint_and_steel", "Lore line.", [check()], [xp(20)])
    CH.q("tools", "First Tools", "minecraft:crafting_table", "Text", [item("minecraft:crafting_table")], [xp(25), item_r("minecraft:bread", 4)], deps=["spark"])
"""
import hashlib, json, os

DIMS = {"overworld": "minecraft:overworld", "nether": "minecraft:the_nether", "end": "minecraft:the_end"}
IMAGE_ALPHA = 140   # chapter backdrop opacity, 0-255 (about 55%)


def hid(*parts):
    """16-hex-digit object id, always below 2^63: FTB Quests parses ids with a signed Long.parseLong(s, 16) (QuestObjectBase.parseHexId), so an id
    with the top bit set fails to parse and silently drops chapter groups and dependency links."""
    return "%016X" % (int(hashlib.md5("|".join(parts).encode()).hexdigest()[:16], 16) & 0x7FFFFFFFFFFFFFFF)


def q(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


# ---- tasks / rewards ---------------------------------------------------------------------------------------------------
def check():
    return {"type": "checkmark"}


def item(item_id, count=1, consume=False):
    return {"type": "item", "item": item_id, "count": count, "consume": consume}


def kill(entity, n=1):
    return {"type": "kill", "entity": entity, "value": n}


def struct(structure):
    return {"type": "structure", "structure": structure}


def dim(dimension):
    return {"type": "dimension", "dim": DIMS.get(dimension, dimension)}


def adv(advancement):
    return {"type": "advancement", "advancement": advancement}


def biome(b):
    return {"type": "biome", "biome": b}


def xp(n):
    return {"type": "xp", "xp": n}


def item_r(item_id, count=1):
    return {"type": "item", "item": item_id, "count": count}


def points(n=1):
    return {"type": "command", "command": "skilltree points add {p} %d" % n, "elevate": True, "silent": True, "label": "%d skill point%s" % (n, "" if n == 1 else "s")}


def cache(tier, label=None):
    """Loot cache reward: loot table aldreth:quest/t<tier> (generated by tools/build_loot.py)."""
    return {"type": "command", "command": "loot give {p} loot aldreth:quest/t%d" % tier, "elevate": True, "silent": True, "label": label or "Tier %d supply cache" % tier}


def cmd(command, label=""):
    return {"type": "command", "command": command, "elevate": True, "silent": True, "label": label}


class Chapter:
    def __init__(self, key, title, icon, group, subtitle="", bg=None, order=0):
        self.key, self.title, self.icon, self.group, self.subtitle, self.bg, self.order = key, title, icon, group, subtitle, bg, order
        self.quests = []
        self.keys = {}

    def q(self, key, title, icon, desc, tasks, rewards, deps=(), shape="circle", size=1.0, optional=False, sub="", x=None, y=None):
        assert key not in self.keys, "duplicate quest key %s in %s" % (key, self.key)
        # structure hunts depend on biome and seed (a plains village can be thousands of blocks away), so they never gate progression. Optional only keeps
        # them out of chapter completion; FTB still makes dependents wait for an optional quest (Quest.areDependenciesComplete), so gating_deps()
        # routes dependents around structure quests. The rewards stay.
        if any(t.get("type") == "structure" for t in tasks):
            optional = True
        d = dict(key=key, title=title, icon=icon, desc=desc if isinstance(desc, list) else [desc], tasks=tasks, rewards=rewards, deps=list(deps), shape=shape,
                 size=size, optional=optional, sub=sub, x=x, y=y)
        self.quests.append(d)
        self.keys[key] = d
        return key


def layout(ch):
    """Layered layout: x by dependency depth, y by parent mean with collision spacing."""
    depth = {}
    for qd in ch.quests:
        for dp in qd["deps"]:
            assert "." in dp or dp in ch.keys, "%s: unknown dep %s in quest %s" % (ch.key, dp, qd["key"])
    order = [qd["key"] for qd in ch.quests]
    for k in order:
        depth[k] = 0
    for _ in range(len(order)):
        changed = False
        for qd in ch.quests:
            local = [x for x in qd["deps"] if "." not in x]
            if local:
                d = 1 + max(depth[x] for x in local)
                if d != depth[qd["key"]]:
                    depth[qd["key"]] = d
                    changed = True
        if not changed:
            break
    cols = {}
    for k in order:
        cols.setdefault(depth[k], []).append(k)
    ypos = {}
    for d in sorted(cols):
        want = []
        for i, k in enumerate(cols[d]):
            deps = [x for x in ch.keys[k]["deps"] if "." not in x]
            want.append((sum(ypos[x] for x in deps) / len(deps) if deps else i * 2.0, i, k))
        want.sort()
        last = -1e9
        for w, i, k in want:
            yy = max(w, last + 1.8)
            ypos[k] = yy
            last = yy
        # re-center column around mean of desired
        if want:
            shift = (sum(w for w, _, _ in want) / len(want)) - (sum(ypos[k] for _, _, k in want) / len(want))
            for _, _, k in want:
                ypos[k] += shift
    for qd in ch.quests:
        k = qd["key"]
        qd["x"] = qd["x"] if qd["x"] is not None else depth[k] * 2.2
        qd["y"] = qd["y"] if qd["y"] is not None else round(ypos[k], 2)
    return depth


def desc_lines(lines):
    return "[" + ", ".join(q(l) for l in lines) + "]"


def task_snbt(ch, qd, i, t):
    tid = hid(ch.key, qd["key"], "t%d" % i)
    out = ['\t\t\t\t\t{', '\t\t\t\t\t\tid: "%s"' % tid, '\t\t\t\t\t\ttype: "%s"' % t["type"]]
    ty = t["type"]
    if ty == "item":
        out += ['\t\t\t\t\t\titem: %s' % q(t["item"]), '\t\t\t\t\t\tcount: %dL' % t["count"] if t["count"] > 2 ** 31 else '\t\t\t\t\t\tcount: %d' % t["count"],
                '\t\t\t\t\t\tconsume_items: %s' % ("true" if t.get("consume") else "false")]
    elif ty == "kill":
        out += ['\t\t\t\t\t\tentity: %s' % q(t["entity"]), '\t\t\t\t\t\tvalue: %d' % t["value"]]
    elif ty == "structure":
        out += ['\t\t\t\t\t\tstructure: %s' % q(t["structure"])]
    elif ty == "dimension":
        out += ['\t\t\t\t\t\tdimension: %s' % q(t["dim"])]   # NBT key is "dimension" ("dim" is only the editor label; FTB read it as "")
    elif ty == "advancement":
        out += ['\t\t\t\t\t\tadvancement: %s' % q(t["advancement"])]
    elif ty == "biome":
        out += ['\t\t\t\t\t\tbiome: %s' % q(t["biome"])]
    out.append('\t\t\t\t\t}')
    return "\n".join(out)


def reward_snbt(ch, qd, i, r):
    rid = hid(ch.key, qd["key"], "r%d" % i)
    out = ['\t\t\t\t\t{', '\t\t\t\t\t\tid: "%s"' % rid, '\t\t\t\t\t\ttype: "%s"' % r["type"]]
    if r["type"] == "xp":
        out.append('\t\t\t\t\t\txp: %d' % r["xp"])
    elif r["type"] == "item":
        out += ['\t\t\t\t\t\titem: %s' % q(r["item"]), '\t\t\t\t\t\tcount: %d' % r["count"]]
    elif r["type"] == "command":
        # elevate_perms: run at permission level 2 (loot give, skilltree, kubejs stages); a non-op player's own level runs none of them
        out += ['\t\t\t\t\t\tcommand: %s' % q(r["command"]), '\t\t\t\t\t\televate_perms: true', '\t\t\t\t\t\tsilent: true']
        if r.get("label"):
            out.append('\t\t\t\t\t\ttitle: %s' % q(r["label"]))
    out.append('\t\t\t\t\t}')
    return "\n".join(out)


def is_structure_quest(qd):
    return any(t.get("type") == "structure" for t in qd["tasks"])


def gating_deps(chapters):
    """Set qd["gate"] (the dependency ids written to SNBT) for every quest so that no structure hunt blocks anything: a dependency on a structure
    quest is replaced by that quest's own dependencies (transitively). The visual layout keeps the design deps. Exception: an exploration capstone
    (checkmark tasks only, every dependency a structure quest, nothing depends on it) keeps its structure dependencies; visiting them is its point."""
    index = {c.key: c for c in chapters}

    def resolve(c, d):
        ck, qk = d.split(".", 1) if "." in d else (c.key, d)
        return index[ck], index[ck].keys[qk]

    depended = {(rc.key, rq["key"]) for c in chapters for qd in c.quests for d in qd["deps"] for rc, rq in [resolve(c, d)]}
    for c in chapters:
        for qd in c.quests:
            targets = [resolve(c, d) for d in qd["deps"]]
            capstone = (targets and all(t["type"] == "checkmark" for t in qd["tasks"]) and all(is_structure_quest(tq) for _, tq in targets)
                        and (c.key, qd["key"]) not in depended)
            out = []

            def add(tc, tq, seen):
                if is_structure_quest(tq) and not capstone:
                    for d2 in tq["deps"]:
                        nc, nq = resolve(tc, d2)
                        if (nc.key, nq["key"]) not in seen:
                            add(nc, nq, seen | {(nc.key, nq["key"])})
                elif hid(tc.key, tq["key"]) not in out:
                    out.append(hid(tc.key, tq["key"]))

            for tc, tq in targets:
                add(tc, tq, {(tc.key, tq["key"])})
            qd["gate"] = out


def dep_id(ch, d):
    """Quest id of a dependency: 'key' is a quest in this chapter, 'chapter.key' a quest in another chapter. FTB silently drops ids that match no quest."""
    return hid(*d.split(".", 1)) if "." in d else hid(ch.key, d)


def quest_snbt(ch, qd):
    qid = hid(ch.key, qd["key"])
    lines = ['\t\t{', '\t\t\tid: "%s"' % qid, '\t\t\ttitle: %s' % q(qd["title"])]
    if qd["sub"]:
        lines.append('\t\t\tsubtitle: %s' % q(qd["sub"]))
    lines += ['\t\t\tdescription: %s' % desc_lines(qd["desc"]), '\t\t\ticon: %s' % q(qd["icon"]), '\t\t\tx: %sd' % qd["x"], '\t\t\ty: %sd' % qd["y"],
              '\t\t\tsize: %sd' % qd["size"], '\t\t\tshape: %s' % q(qd["shape"])]
    lines.append("\t\t\ttasks: [\n" + ",\n".join(task_snbt(ch, qd, i, t) for i, t in enumerate(qd["tasks"])) + "\n\t\t\t]")
    lines.append("\t\t\trewards: [" + ("\n" + ",\n".join(reward_snbt(ch, qd, i, r) for i, r in enumerate(qd["rewards"])) + "\n\t\t\t]" if qd["rewards"] else "]"))
    if qd["optional"]:
        lines.append('\t\t\toptional: true')
    deps = qd["gate"] if "gate" in qd else [dep_id(ch, d) for d in qd["deps"]]
    if deps:
        lines.append("\t\t\tdependencies: [" + ", ".join('"%s"' % d for d in deps) + "]")
    lines.append('\t\t}')
    return "\n".join(lines)


def chapter_snbt(ch, group_ids, idx, image=None):
    cid = hid(ch.key)
    out = ['{', '\tid: "%s"' % cid, '\tfilename: %s' % q("%02d_%s" % (idx, ch.key)), '\ttitle: %s' % q(ch.title)]
    if ch.subtitle:
        out.append('\tsubtitle: %s' % q(ch.subtitle))
    out += ['\ticon: %s' % q(ch.icon), '\torder_index: %d' % idx, '\tgroup: "%s"' % group_ids[ch.group], '\tdefault_quest_shape: "circle"', '\tdefault_quest_size: 1.0d',
            '\tdefault_hide_dependency_lines: false', '\tprogression_mode: "flexible"']
    if image:
        # x/y is the image center; alpha is an int 0-255 (ChapterImage.readData uses getInt, so 0.55d was read as 0 = invisible)
        out.append("\timages: [{\n\t\t\tx: %sd\n\t\t\ty: %sd\n\t\t\twidth: %sd\n\t\t\theight: %sd\n\t\t\trotation: 0.0d\n\t\t\timage: %s\n\t\t\torder: 0\n\t\t\talpha: %d\n\t\t}]"
                   % (image + (IMAGE_ALPHA,)))
    out.append("\tquests: [\n" + ",\n".join(quest_snbt(ch, qd) for qd in ch.quests) + "\n\t]")
    out.append('}')
    return "\n".join(out) + "\n"


def validate(ch, reg, errors):
    import custom_items
    R = {"item": set(reg["item"]) | set(custom_items.ITEMS), "entity": set(reg["entity_type"]), "structure": set(reg["structure"]), "biome": set(reg["biome"]),
         "dimension": set(reg["dimension"]) | set(DIMS.values()), "advancement": set(reg.get("advancement", []))}
    for qd in ch.quests:
        loc = "%s/%s" % (ch.key, qd["key"])
        if qd["icon"] not in R["item"]:
            errors.append("%s: icon %s unknown" % (loc, qd["icon"]))
        for t in qd["tasks"]:
            ty = t["type"]
            if ty == "item" and t["item"] not in R["item"]:
                errors.append("%s: task item %s unknown" % (loc, t["item"]))
            elif ty == "kill" and t["entity"] not in R["entity"]:
                errors.append("%s: task entity %s unknown" % (loc, t["entity"]))
            elif ty == "structure" and t["structure"] not in R["structure"]:
                errors.append("%s: task structure %s unknown" % (loc, t["structure"]))
            elif ty == "biome" and t["biome"] not in R["biome"]:
                errors.append("%s: task biome %s unknown" % (loc, t["biome"]))
            elif ty == "dimension" and t["dim"] not in R["dimension"]:
                errors.append("%s: task dimension %s unknown" % (loc, t["dim"]))
            elif ty == "advancement" and R["advancement"] and t["advancement"] not in R["advancement"]:
                errors.append("%s: task advancement %s unknown" % (loc, t["advancement"]))
        for r in qd["rewards"]:
            if r["type"] == "item" and r["item"] not in R["item"]:
                errors.append("%s: reward item %s unknown" % (loc, r["item"]))
