"""Tiered structure spacing through Sparse Structures Reforged (the one spacing system; Structurify stays neutral).
Every structure_set in the registry snapshot gets an explicit spread factor from its tier (factor multiplies spacing+separation). Tier rules live in
tools/spacing_tiers.py; calibrated factors come from tools/calibrate_spacing.py (config/aldreth/spacing_calibration.json).
Writes config/sparsestructures.json5 and the tier table into docs/WORLDGEN.md. Usage: python tools/tune_structures.py"""
import collections, json, os, re, sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import spacing_tiers as ST  # noqa: E402

SETS = sorted(json.load(open(os.path.join(ROOT, "pack", "registries_snapshot.json"), encoding="utf-8"))["structure_set"])
F = ST.factors()
assign, counts = {}, collections.Counter()
for s in SETS:
    t = ST.classify(s)
    assign[s] = (t, F[t])
    counts[t] += 1

custom = [{"structure": s, "factor": f} for s, (t, f) in assign.items() if f != ST.DEFAULT_FACTOR]
body = {"spreadFactor": ST.DEFAULT_FACTOR, "customSpreadFactors": custom}
txt = ("// Generated by tools/tune_structures.py (tiered spacing; edit the tools, not this file). Requires a restart; affects new chunks only.\n"
       + json.dumps(body, indent=2) + "\n")
open(os.path.join(ROOT, "config", "sparsestructures.json5"), "w", encoding="utf-8").write(txt)

cal = os.path.join(ROOT, "config", "aldreth", "spacing_calibration.json")
note = ""
if os.path.isfile(cal):
    c = json.load(open(cal, encoding="utf-8"))
    note = "\n\nFactors are **calibrated from a measured census** (`tools/structure_census.py` over %s km2 of generated overworld, `tools/calibrate_spacing.py`): density scales as 1/factor^2, so each tier's factor is sqrt(measured density at factor 1 / target density)." % c.get("area_km2")
rows = ["| Tier | Factor | Target /km2 | Sets | Meaning |", "|---|---|---|---|---|"]
meaning = {t: w for t, _, w, _ in ST.TIERS}
meaning["default"] = "anything unlisted (new mods default here)"
for t in [x[0] for x in ST.TIERS] + ["default"]:
    rows.append("| %s | %.2fx | %s | %d | %s |" % (t, F[t], ST.TARGETS.get(t, "n/a"), counts[t], meaning[t]))
table = "\n".join(rows)
dp = os.path.join(ROOT, "docs", "WORLDGEN.md")
d = open(dp, encoding="utf-8").read()
block = ("<!-- spacing:begin -->\n## Structure spacing tiers (generated by tools/tune_structures.py)\nSparse Structures Reforged multiplies each set's spacing and separation; "
         "Structurify is installed but neutral (one spacing system only). Strongholds use rings and are unaffected. Targets are starts per km2 (1000x1000 blocks) in the overworld." + note + "\n\n" + table + "\n<!-- spacing:end -->")
d = re.sub(r"<!-- spacing:begin -->.*?<!-- spacing:end -->", lambda m: block, d, flags=re.S) if "<!-- spacing:begin -->" in d else d.rstrip() + "\n\n" + block + "\n"
open(dp, "w", encoding="utf-8").write(d)
print(dict(counts), "| custom entries:", len(custom), "| factors:", {k: round(v, 2) for k, v in F.items()})
