"""Tiered structure spacing through Sparse Structures Reforged (the one spacing system; Structurify stays neutral).
Every structure_set in the registry snapshot gets an explicit spread factor from its tier (factor multiplies spacing+separation).
Writes config/sparsestructures.json5 and the tier table into docs/WORLDGEN.md. Usage: python tools/tune_structures.py"""
import collections, json, os, re

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SETS = sorted(json.load(open(os.path.join(ROOT, "pack", "registries_snapshot.json"), encoding="utf-8"))["structure_set"])
DEFAULT = 1.8
# (tier, factor, why, regex on structure_set id) - first match wins
TIERS = [
    ("realm", 1.0, "dimension-designed layouts (Twilight Forest, Aether family, Blue Skies, Undergarden, Otherside, End); untouched",
     r"^(twilightforest|aether|aether_redux|ancient_aether|deep_aether|lost_aether_content|blue_skies|undergarden|deeperdarker|nullscape|endrem|betterendisland):|^minecraft:(end_cities|strongholds)$"),
    ("boss", 1.25, "progression bosses and quest targets: must stay findable",
     r"^(cataclysm|soulsweapons|ender_dragon_loot|bosses_of_mass_destruction|block_factorys_bosses|mowziesmobs|aquamirae|iceandfire|eeeabsmobs|illagerinvasion|undead_revamp2):"),
    ("settlement", 1.3, "villages and towns: rest stops, traders, bounties",
     r"(village|town|tidal|hamlet|settlement|outpost_village)|^(towns_and_towers|medieval_buildings):houses|^towns_and_towers:"),
    ("great", 1.6, "mega-dungeons: rare by design already, keep them reachable",
     r"^(dungeons_arise|dungeons_arise_seven_seas|prodigium_dungeons|irons_spellbooks|goety|betterdungeons|betterstrongholds|betterfortresses|betteroceanmonuments|betterdeserttemples|betterjungletemples|betterwitchhuts):"),
    ("vanilla", 1.5, "vanilla structures (mansions, monuments, temples, ruined portals) and their replacements", r"^(minecraft|bettermineshafts|trials):"),
    ("dungeon", 2.0, "medium dungeons and towers: the bread and butter of exploration",
     r"^(dungeons_enhanced|dungeons_plus|born_in_chaos_v1|explorify|repurposed_structures|dungeoncrawl|ati_structures|structory|structory_towers|valhelsia_structures|hopo|betterarcheology|formationsnether|formationsoverworld|bygonenether|incendium|nova_structures|terrariastructures):"),
    ("clutter", 2.6, "small ruins, wells, camps and decor: spaced out so discoveries feel deliberate",
     r"^(mvs|mns|mss|mes|supplementaries|twigs|wabi_sabi_structures|additionalstructures|philipsruins|red|underground_rooms|farmers_structures|meadow|beautify|verdantvibes|species|friendsandfoes|splendid_slimes|tameablebeasts|paraglider|biomeswevegone|terralith|alexscaves|apotheosis):"),
]

assign, counts = {}, collections.Counter()
for s in SETS:
    for tier, f, _, rx in TIERS:
        if re.search(rx, s):
            break
    else:
        tier, f = "default", DEFAULT
    assign[s] = (tier, f)
    counts[tier] += 1

custom = [{"structure": s, "factor": f} for s, (t, f) in assign.items() if f != DEFAULT]
body = {"spreadFactor": DEFAULT, "customSpreadFactors": custom}
txt = ("// Generated by tools/tune_structures.py (tiered spacing; edit the tool, not this file). Requires a restart; affects new chunks only.\n"
       + json.dumps(body, indent=2) + "\n")
open(os.path.join(ROOT, "config", "sparsestructures.json5"), "w", encoding="utf-8").write(txt)

# docs
rows = ["| Tier | Factor | Sets | Meaning |", "|---|---|---|---|"]
for tier, f, why, _ in TIERS + [("default", DEFAULT, "anything unlisted (new mods default here)", "")]:
    rows.append("| %s | %.2fx | %d | %s |" % (tier, f, counts[tier], why))
table = "\n".join(rows)
dp = os.path.join(ROOT, "docs", "WORLDGEN.md")
d = open(dp, encoding="utf-8").read()
block = "<!-- spacing:begin -->\n## Structure spacing tiers (generated by tools/tune_structures.py)\nSparse Structures Reforged multiplies each set's spacing and separation; Structurify is installed but neutral (one spacing system only). Strongholds use rings and are unaffected.\n\n" + table + "\n<!-- spacing:end -->"
d = re.sub(r"<!-- spacing:begin -->.*?<!-- spacing:end -->", lambda m: block, d, flags=re.S) if "<!-- spacing:begin -->" in d else d.rstrip() + "\n\n" + block + "\n"
open(dp, "w", encoding="utf-8").write(d)
print(dict(counts), "| custom entries:", len(custom))
