"""Generate docs/MODLIST.md and pack/manifest.json from pack/mods.lock.json (+ candidate notes). Only shipping statuses are listed.
Usage: python tools/write_modlist.py [--status core,std,dep,test]"""
import json, os, re, sys, datetime, collections
ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
status = set((sys.argv[sys.argv.index("--status") + 1] if "--status" in sys.argv else "core,std,dep,test").split(","))
lock = json.load(open(os.path.join(ROOT, "pack", "mods.lock.json"), encoding="utf-8"))
notes = {}
for ln in open(os.path.join(ROOT, "pack", "candidates.txt"), encoding="utf-8"):
    p = [x.strip() for x in ln.split("|")]
    if len(p) >= 4 and not ln.startswith("#"):
        notes[re.sub(r"\s+", " ", p[1].split("::")[0]).lower()] = p[3]
rej = os.path.join(ROOT, "pack", "rejects.txt")
rejected = {l.split("|")[0].strip().lower() for l in open(rej, encoding="utf-8") if l.strip() and not l.startswith("#")} if os.path.isfile(rej) else set()
norm = lambda n: re.sub(r"\s+", " ", re.sub(r"\s*[\[\(].*?[\]\)]", "", n or "")).strip().lower()
rows = [e for e in lock if e["status"] in status and norm(e["name"]) not in rejected]
CAT = dict(perf="Performance/fixes", qol="QoL/UI", vis="Visual/audio", rpg="RPG systems", acc="Accessories", combat="Combat/weapons/armor",
           magic="Magic", mobs="Mobs/bosses", struct="Structures", world="Worldgen/dimensions", trav="Mounts/traversal", food="Food/farming",
           build="Building/storage", script="Scripting", lib="Libraries", misc="Misc")
by = collections.defaultdict(list)
for e in rows:
    by[CAT.get(e["category"], e["category"])].append(e)
out = ["# Mod list", "", "_Generated by `tools/write_modlist.py` from `pack/mods.lock.json` on %s. Do not edit by hand._" % datetime.date.today(), "",
       "**%d mods** (%d content/QoL picks, %d libraries/dependencies). Machine-readable: `pack/manifest.json`." % (len(rows), sum(1 for e in rows if e["why"] == "candidate"), sum(1 for e in rows if e["why"] != "candidate")), ""]
for cat in sorted(by):
    out += ["## %s (%d)" % (cat, len(by[cat])), "", "| Mod | Version file | Status | Note |", "|---|---|---|---|"]
    for e in sorted(by[cat], key=lambda x: x["name"].lower()):
        n = notes.get(norm(e["name"]), e["why"] if e["why"] != "candidate" else "")
        src = ("CF:%s" % e["addonID"]) if e["addonID"] > 0 else "MR"
        out.append("| %s | `%s` (%s) | %s | %s |" % (e["name"].replace("|", "/"), e["fileName"], src, e["status"], n))
    out.append("")
open(os.path.join(ROOT, "docs", "MODLIST.md"), "w", encoding="utf-8").write("\n".join(out))
man = dict(pack="Embers of Aldreth", minecraft="1.20.1", loader="forge", loaderVersion="47.4.10", generated=str(datetime.date.today()),
           count=len(rows), mods=[dict(name=e["name"], file=e["fileName"], sha1=e["sha1"], curseforgeProject=e["addonID"] if e["addonID"] > 0 else None,
                                       curseforgeFile=e.get("fileId"), url=e["url"], category=e["category"], status=e["status"]) for e in rows])
json.dump(man, open(os.path.join(ROOT, "pack", "manifest.json"), "w", encoding="utf-8"), indent=1, ensure_ascii=False)
print("modlist:", len(rows), "mods")
